### ISSUE TITLE
Data variables brainstorming

### ISSUE THREAD

**Issue by Cyberzoid1** [uidaho/smartsettia-unit#1]
Can you take a look at this and see if i'm missing any settings, or data that needs to be stored,sent, or received?
Doing some brainstorming.
https://github.com/uidaho/smartsettia-unit/blob/development/my_globals.py

**Comment by brec9824** [comment]
I don't think you really need the name of the device since the pi serial number and key (essentially a password) will be enough to identify the device. Also how we have the schedule (not implemented yet) there might be multiple times throughout the day the cover opens and closes. So 
`"Cover_schedual_open": "somedata",  # open time`
`"Cover_schedual_close": "somedata",}# close time`
will need to be an array(or something similar) of times.
Also webcam picture should be binary.

**Comment by Cyberzoid1** [comment]
The name would probably only be used on a debugging webpage. No other practical use.

For the cover schedule, I thought we decided we were only doing a single open and close event?

**Comment by brec9824** [comment]
Right now the database table for schedules allows for multiple open and close times for a day, but that schedule is used for every single day. So everyday of the week has the same schedule.

**Comment by brandonjank** [comment]
The device should POST to https://smartsettia.com/api/ping with content type "application/json" a json formatted string, for now, like:
```json
{"token": "aSDf7986a89s7df87asd98f7dd", "uuid": "4dbc0776-9b44-11e7-abc4-cec278b6b50a", "version": "0.1.1", "name": "Unit Alpha", "hostname": "device.local", "ip": "192.168.1.213", "time": "YYYY-MM-DD HH:MM:SS", "status": "closed", "error_msg": "", "cpu_temp": "30", "temperature": "28", "humidity": "34", "light_in": "0", "light_out": "100", "switch_open": "0", "switch_closed": "1", "open_time": "HH:MM:SS", "close_time": "HH:MM:SS", "ping_time": "60"}
```

- token: think long random alphanumeric password
- uuid: A Version 1 UUID is a universally unique identifier that is generated using the MAC address of the computer on which it was generated.
- version: semantic versioning string of the device http://semver.org/
- name: what the unit thinks it's name is
- hostname: the /etc/hostname of the pi
- ip: the IPv4 of the pi
- time: the time and date formatted YYYY-MM-DD HH:MM:SS
- status: string value of the device's status. can be: opening, closing, open, closed, locked, error
- error_msg: string description of the error, empty if none
- cpu_temp: pi temperature in C
- temperature: temp sensor temperature in C
- humidty: humidity sensor. in 0-100 %
- light_in: light sensor inside awning. 0-100 %
- light_out: light sensor outside awning. 0-100 %
- switch_open: should be 1 when unit is in open position according to the limit switch.
- switch_closed: should be 1 when unit is in closed position accoring to the limit switch.
- open_time: the time the device should open HH:MM:SS
- close_time: the time the device should close HH:MM:SS
- ping_time: the interval between the the next time the device posts data in seconds.

The server with then validate the post request and respond with a json string which we can determine later.

**Comment by Cyberzoid1** [comment]
All i'm getting back is the api page error
https://pastebin.com/NZ2zK1t1

**Comment by brandonjank** [comment]
```php
<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class AddStatesToDevicesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('devices', function (Blueprint $table) {
            // token: think long random alphanumeric password
            $table->string('token')->nullable();
            // uuid: A Version 1 UUID is a universally unique identifier that is generated using the MAC address of the computer on which it was generated.
            $table->uuid('uuid')->nullable();
            // version: semantic versioning string of the device http://semver.org/
            $table->string('version')->nullable();
            // hostname: the /etc/hostname of the pi
            $table->string('hostname')->nullable();
            // ip: the IPv4 of the pi
            $table->ipAddress('ip')->nullable();
            // mac_address: 
            $table->macAddress('mac_address')->nullable();
            // time: the time and date formatted YYYY-MM-DD HH:MM:SS
            $table->dateTime('time')->nullable();
            // timezone:
            $table->integer('timezone')->default(-8);
            // status: string value of the device's status. can be: opening, closing, open, closed, locked, error
            $table->enum('status', ['opening', 'closing', 'open', 'closed', 'locked', 'error'])->nullable();
            // error_msg: string description of the error, empty if none
            $table->text('error_msg')->nullable();
            // light_in: light sensor inside awning. 0-100 %
            $table->integer('light_in')->nullable();
            // light_out: light sensor outside awning. 0-100 %
            $table->integer('light_out')->nullable();
            // switch_open: should be 1 when unit is in open position according to the limit switch.
            $table->boolean('switch_open')->nullable();
            // switch_closed: should be 1 when unit is in closed position accoring to the limit switch.
            $table->boolean('switch_closed')->nullable();
            // open_time: the time the device should open HH:MM:SS
            $table->time('open_time')->default('08:00:00');
            // close_time: the time the device should close HH:MM:SS
            $table->time('close_time')->default('17:00:00');
            // ping_time: the interval between the the next time the device posts data in seconds.
            $table->integer('ping_time')->default(60);
            // TEMPORARY: these will get moved to sensors table
            // cpu_temp: pi temperature in C
            $table->integer('cpu_temp')->nullable();
            // temperature: temp sensor temperature in C
            $table->integer('temperature')->nullable();
            // humidty: humidity sensor. in 0-100 %
            $table->integer('humidty')->nullable();
        });
    }
    
    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('devices', function (Blueprint $table) {
            $table->dropColumn('token','uuid','version','hostname','ip','mac_address','time','timezone','status','error_msg','light_in','light_out','switch_open','switch_closed','open_time','close_time','ping_time');
        });
    }
}

```
